### ISSUE TITLE
wrong name for qudt/quantitykind

### ISSUE THREAD

**Issue by VladimirAlexiev** [TriplyDB/TriplyDB-JS#1]
https://triplydb.com/qudt/quantitykind says "QUDT Dimension Vectors". 
I don't know where this comes from since https://triplydb.com/qudt/quantitykind/table shows the correct label "QUDT VOCAB Quantity Kinds  Release 2.1"

**Comment by rubenw** [comment]
That title comes from this file: https://github.com/TriplyDB/YALC/blob/master/datasets/quantitykind@2.1.2.json
The `url` field in that file says where the data is from.

**Comment by LaurensRietveld** [comment]
Hi @VladimirAlexiev , just to add some context to what @rubenw said. 

This dataset is automatically uploaded by a script that automatically publishes datasets on triplydb.com. If you have suggestions for metadata improvements, you are of course welcome to make a PR  (see [here](https://github.com/TriplyDB/YALC) for more information on how to contribute to YALC)

About your reference to the version number: the version number is also included in the dataset description, on [this](https://triplydb.com/qudt/quantitykind) page.

I'm closing this issue, but if you have other questions related to this dataset, feel free to open an issue on the [YALC](https://github.com/TriplyDB/YALC) repository

**Comment by VladimirAlexiev** [comment]
fixed in https://github.com/TriplyDB/YALC/pull/2
