### ISSUE TITLE
Issue installing TriplyDB due to @triply/utils missing from NPM repositories

### ISSUE THREAD

**Issue by vemonet** [TriplyDB/TriplyDB-JS#10]
Hi @RossCurry and @LaurensRietveld , since this morning we cannot install TriplyDB anymore (it was still working yesterday, the 10 march 2022)

This is the error we get when running `yarn` 

```bash  
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@triply/utils/-/utils-1.3.88.tgz: Request failed \"404 Not Found\"".
```

We also tried to install with different NPM registry (yarnpkg, npmjs...) and versions of `@triply/utils`, but we always get the same error

It's quite problematic as it prevents to use many packages and frameworks (RATT, LDWizard, etc)

Any idea what it is due to? And how it could be fixed? Maybe there was a change in the permissions for `@triply/utils`?

Thanks a lot!

**Comment by LaurensRietveld** [comment]
Apologies, could you try again? It seems that dependency was accidentally set to private. It's now public again

**Comment by vemonet** [comment]
Thanks a lot @LaurensRietveld ! It's now working again
