### ISSUE TITLE
Add feature to set JSON-LD Frame for SPARQL Queries

### ISSUE THREAD

**Issue by mightymax** [TriplyDB/TriplyDB-JS#29]
In TriplyDB there is a feature in the SPARQL IDE to switch to JSON-LD Frame editor for a saved Query. In this view users can paste a JSON-LD Frame which is somehow stored with that query. It does not seem possible to store this frame and the SPARQL IDE state that comes with it using TriplyDB-JS. It look like it is thus impossible to programmatically create a SPARQL Query in an account making use of this feature.

**Expected behavior:**
- Documentation on how to save a JSON-LD Frame when creating or changing a saved SPARQL Query.
- Support for adding JSON-LD Frames in the API and TriplyDB-JS

**Comment by ivan-kovatchev** [comment]
Thanks for reporting this @mightymax ! We're looking into this, and should have this feature ready within two weeks.

**Comment by charitha93** [comment]
Fixed in https://github.com/TriplyDB/TriplyDB-JS/pull/31
Released in v7.1.0

@mightymax
