### ISSUE TITLE
Change default behaviour when uploading an asset with a name that already exists 

### ISSUE THREAD

**Issue by kathrinrin** [TriplyDB/TriplyDB-JS#37]
# Observed 

`dataset.uploadAsset()` emits the following error message when trying to upload an asset that is already stored:

`Tried to add asset '[ASSET NAME]' to dataset [DATASET], but an asset with that name already exists.` 

This leads to the following workaround: 
1) Delete the asset in case it is there with a try/catch 
2) Upload the asset 

I also tested the alternative route to add a new version with `asset.addVersion()`, but this only works in case a previous version already exists, otherwise the following error message is emitted: 

`Failed to get asset [ASSET NAME] from dataset [DATASET].` 

# Expected 

I would expect that by default, the asset is created if it does not exist yet, and that otherwise the latest version is overwritten.

**Comment by ivan-kovatchev** [comment]
Changing the default behaviour would be a breaking change that would need a bit more justification. Two other options I could see are:
- We could add a `dataset.overwriteAsset()` function, with the behaviour you specify. Note that we don't have this functionality for any other methods. Most are `ensure...()` which don't overwrite something, so it seems a bit application-specific.
- You could write a helper function similar to this, e.g.:
  ```js
  async function overwriteAsset(dataset: Dataset, assetName: string, assetFile: string) {
    try {
      await dataset.uploadAsset(assetName, assetFile);
    } catch (e) {
      if (e instanceOf TriplyDbJsError && e.statusCode === 409) {
         const asset = await dataset.getAsset(assetName);
         await asset.delete();
         await dataset.uploadAsset(assetName, assetFile);
      } else {
       throw e;
      }
    }
  }
  ```

**Comment by kathrinrin** [comment]
Thank you for the ideas! I fear the a function called `overwriteAsset()` is a bit misleading, as users might expect that the asset needs to already exist in order to be overwritten.

**Comment by dionenak** [comment]
This issue was solved, you can see the [documentation](https://docs.triply.cc/triplydb-js/dataset/#datasetuploadasset-filepath-string-opts-mode-throw-if-exists-replace-if-exists-append-version-name-string) for the new interface of uploadAsset()
